ci(tools): update git-release-notes to generate a full change log

diff --git a/scripts/git-release-notes b/scripts/git-release-notes
--- a/scripts/git-release-notes
+++ b/scripts/git-release-notes
@@ -1,47 +1,120 @@
 #!/bin/bash
 
+declare mode="${1:-latest}"
+
 git_get_tags() {
-	git tag | sort -Vr | grep -E '^v[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+$'
+	local tag="${1:-}"
+
+	if [[ -z ${tag} ]]; then
+		git tag | sort -Vr | grep -E '^v[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+$'
+	else
+		git tag | sort -Vr | grep -E '^v[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+$' | grep -A 1 "${tag}"
+	fi
 } # git_get_tags()
 
 git_get_tag_previous() {
-	git_get_tags | head -n 2 | tail -n 1
+	local tag="${1:-}"
+
+	git_get_tags "${tag}" | head -n 2 | tail -n 1
 } # git_get_tag_previous()
 
 git_get_tag_latest() {
-	git_get_tags | head -n 1
+	local tag="${1:-}"
+
+	git_get_tags "${tag}" | head -n 1
 } # git_get_tag_latest()
 
 git_cl() {
+	local tag="${1:-}"
+
 	local tag_previous
 	local tag_latest
+	local git_ref
 
-	tag_previous="$(git_get_tag_previous)"
-	tag_latest="$(git_get_tag_latest)"
+	if [[ ${tag} =~ ^v0.0.0\^$ ]]; then
+		git_ref="${tag}"
+	else
+		tag_previous="$(git_get_tag_previous "${tag}")"
+		tag_latest="$(git_get_tag_latest "${tag}")"
 
-	git log --pretty=format:'- %s' --abbrev-commit --decorate "${tag_previous}..${tag_latest}"
+		git_ref="${tag_previous}..${tag_latest}"
+	fi
+
+	git log --pretty=format:'- %s' --abbrev-commit --decorate "${git_ref}"
 } # git_cl()
 
-get_release_title() {
-	git_cl | head -n 1 | sed -r -e 's/^- release: (v[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+) - /# Release \1: /g'
+get_release_heading() {
+	local tag="${1:-}"
+
+	git log --pretty=format:'## [%as] ' --abbrev-commit --decorate -n 1 "${tag}"
+
+	if [[ ${tag} == v0.0.0^ ]]; then
+		printf "Release v0.0.0: initial release\n"
+	else
+		git_cl "${tag}" | head -n 1 | sed -r -e 's/^- release: (v[[:digit:]]+[.][[:digit:]]+[.][[:digit:]]+) (- )?/Release \1: /g'
+	fi
 }
 
+filter_commits() {
+	grep -v -e 'Initial commit' -e 'Merge pull request'
+} # filter_commits()
+
 get_release_body() {
+	local tag="${1:-}"
+
 	local -a sections
 
-	mapfile -t sections < <(git_cl | grep -v -E "^- release: " | awk '{ print $2 }' | tr -d ":" | sort -Vu)
+	mapfile -t sections < <(git_cl "${tag}" | grep -v -E "^- release: " | filter_commits | awk '{ print $2 }' | tr -d ":" | sort -Vu)
 
 	for section in "${sections[@]}"; do
 		printf "\n"
-		printf -- "## %s\n" "${section,,}"
+		printf -- "### %s\n" "${section,,}"
 		printf "\n"
-		git_cl | grep -v -E "^- release: " | sort -k 2,2 -V | grep -- "- ${section}: " | sed -r -e 's/^- [[:alpha:]].*: /- /g'
+		git_cl "${tag}" | grep -v -E "^- release: " | filter_commits | sort -k 2,2 -V | grep -- "- ${section}: " | sed -r -e 's/^- [[:alpha:]].*: /- /g'
 	done
 }
 
 create_release_notes() {
-	get_release_title
-	get_release_body
+	local mode="${1}"
+
+	local first="true"
+	local -a tags
+
+	if [[ ${mode} == latest ]]; then
+		mapfile -t tags < <(git_get_tag_latest)
+	elif [[ ${mode} =~ ^v[0-9]+[.][0-9]+[.][0-9]+$ ]]; then
+		if ! git tag | grep -q -E "^${mode}$"; then
+			printf "ERROR: tag [%s] doesn't exist!\n" "${mode}"
+			exit 1
+		fi
+
+		mapfile -t tags < <(printf "%s\n" "${mode}")
+	else
+		printf "# Release Notes\n"
+		printf "\n"
+
+		mapfile -t tags < <(git_get_tags | sort -Vr)
+	fi
+
+	for tag in "${tags[@]}"; do
+		if [[ ${tag} == v0.0.0 ]]; then
+			tag="${tag}^"
+		fi
+
+		if "${first}"; then
+			first="false"
+		else
+			printf "\n"
+		fi
+
+		get_release_heading "${tag}"
+		get_release_body "${tag}"
+	done
 } # create_release_notes()
 
-create_release_notes
+if [[ ${mode} =~ ^(|latest|all|v[0-9]+[.][0-9]+[.][0-9]+)$ ]]; then
+	create_release_notes "${mode}"
+else
+	printf "Usage: %s ^(|latest|all|v[0-9]+[.][0-9]+[.][0-9]+)$\n" "$0"
+	exit 1
+fi
